// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1, arg2) {
  return window['go']['main']['App']['AddToQueue'](arg1, arg2);
}

export function GetDefaultDownloadPath() {
  return window['go']['main']['App']['GetDefaultDownloadPath']();
}

export function GetQueue() {
  return window['go']['main']['App']['GetQueue']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PauseDownloads() {
  return window['go']['main']['App']['PauseDownloads']();
}

export function PauseSingleDownload(arg1) {
  return window['go']['main']['App']['PauseSingleDownload'](arg1);
}

export function RemoveFromQueue(arg1) {
  return window['go']['main']['App']['RemoveFromQueue'](arg1);
}

export function SelectDownloadFolder() {
  return window['go']['main']['App']['SelectDownloadFolder']();
}

export function SelectDownloadFolderWithDefault(arg1) {
  return window['go']['main']['App']['SelectDownloadFolderWithDefault'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function StartDownloads() {
  return window['go']['main']['App']['StartDownloads']();
}

export function StartSingleDownload(arg1) {
  return window['go']['main']['App']['StartSingleDownload'](arg1);
}

export function UpdateSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2, arg3);
}
